const data = {
  song: {
    name: "Eğri eğri, doğru doğru",
    artist: "Barış Manço",
    art_cover: "baris_manco_egri_egri_dogru_dogru.jpeg",
    file: "baris_manco_egri_egri_dogru_dogru.mp3",
    track_length: 0,
  },
  song: {
    name: "Elephant Gun",
    artist: "Beirut",
    art_cover: "beirut_elephant_gun.jpeg",
    file: "beirut_elephant_gun.mp3",
    track_length: 0,
  },
  song: {
    name: "Here with Me",
    artist: "D4vd",
    art_cover: "d4vd_here_with_me.jpeg",
    file: "d4vd_here_with_me.mp3",
    track_length: 242,
  },
  song: {
    name: "A Hard Day's Night",
    artist: "D.E.F Orkestra",
    art_cover: "def_orkestra_a_hard_days_night.jpeg",
    file: "def_orkestra_a_hard_days_night.mp3",
    track_length: 0,
  },
  song: {
    name: "Seeing Hands",
    artist: "Dengue Fever",
    art_cover: "dengue_fever_seeing_hands.jpeg",
    file: "dengue_fever_seeing_hands.mp3",
    track_length: 0,
  },
  song: {
    name: "Bir Yaralı Kuştum",
    artist: "Gaye Su Akyol",
    art_cover: "gaye_su_akyol_bir_yarali_kustum.jpeg",
    file: "gaye_su_akyol_bir_yarali_kustum.mp3",
    track_length: 0,
  },
  song: {
    name: "Adımız Miskindir Bizim",
    artist: "Mazhar ve Fuat",
    art_cover: "mazhar_fuat_adimiz_miskindir_bizim.jpeg",
    file: "mazhar_fuat_adimiz_miskindir_bizim.mp3",
    track_length: 0,
  },
  song: {
    name: "Public Displays of Affection",
    artist: "Morcheeba",
    art_cover: "morcheeba_public_displays_of_affection.jpeg",
    file: "morcheeba_public_displays_of_affection.mp3",
    track_length: 0,
  },
  song: {
    name: "Azize Diskotekte",
    artist: "Osman İşmen",
    art_cover: "osman_ismen_orkestrasi_azize_diskotekte.jpeg",
    file: "osman_ismen_orkestrasi_azize_diskotekte.mp3",
    track_length: 0,
  },
};
