const data = {
  imagePath: "/img/",
  mediaPath: "/media/",
  tracks: [
    {
      name: "Say Say Say",
      artist: "Paul McCartney, Michael Jackson",
      art_cover: "paul_mccartney_michael_jackson_say_say_say.jpeg",
      thumbnail: "paul_mccartney_michael_jackson_say_say_say-thumbnail.jpeg",
      file: "paul_mccartney_michael_jackson_say_say_say.mp3",
    },
    {
      name: "Fade into You",
      artist: "Mazzy Star",
      art_cover: "mazzy_star_fade_into_you.jpeg",
      thumbnail: "mazzy_star_fade_into_you-thumbnail.jpeg",
      file: "mazzy_star_fade_into_you.mp3",
    },
    {
      name: "Eğri eğri, doğru doğru",
      artist: "Barış Manço",
      art_cover: "baris_manco_egri_egri_dogru_dogru.jpeg",
      thumbnail: "baris_manco_egri_egri_dogru_dogru-thumbnail.jpeg",
      file: "baris_manco_egri_egri_dogru_dogru.mp3",
    },
    {
      name: "Elephant Gun",
      artist: "Beirut",
      art_cover: "beirut_elephant_gun.jpeg",
      thumbnail: "beirut_elephant_gun-thumbnail.jpeg",
      file: "beirut_elephant_gun.mp3",
    },
    {
      name: "Here with Me",
      artist: "D4vd",
      art_cover: "d4vd_here_with_me.jpeg",
      thumbnail: "d4vd_here_with_me-thumbnail.jpeg",
      file: "d4vd_here_with_me.mp3",
    },
    {
      name: "A Hard Day's Night",
      artist: "D.E.F Orkestra",
      art_cover: "def_orkestra_a_hard_days_night.jpeg",
      thumbnail: "def_orkestra_a_hard_days_night-thumbnail.jpeg",
      file: "def_orkestra_a_hard_days_night.mp3",
    },
    {
      name: "Seeing Hands",
      artist: "Dengue Fever",
      art_cover: "dengue_fever_seeing_hands.jpeg",
      thumbnail: "dengue_fever_seeing_hands-thumbnail.jpeg",
      file: "dengue_fever_seeing_hands.mp3",
    },
    {
      name: "Bir Yaralı Kuştum",
      artist: "Gaye Su Akyol",
      art_cover: "gaye_su_akyol_bir_yarali_kustum.jpeg",
      thumbnail: "gaye_su_akyol_bir_yarali_kustum-thumbnail.jpeg",
      file: "gaye_su_akyol_bir_yarali_kustum.mp3",
    },
    {
      name: "Adımız Miskindir Bizim",
      artist: "Mazhar ve Fuat",
      art_cover: "mazhar_fuat_adimiz_miskindir_bizim.jpeg",
      thumbnail: "mazhar_fuat_adimiz_miskindir_bizim-thumbnail.jpeg",
      file: "mazhar_fuat_adimiz_miskindir_bizim.mp3",
      track_length: 0,
    },
    {
      name: "Public Displays of Affection",
      artist: "Morcheeba",
      art_cover: "morcheeba_public_displays_of_affection.jpeg",
      thumbnail: "morcheeba_public_displays_of_affection-thumbnail.jpeg",
      file: "morcheeba_public_displays_of_affection.mp3",
    },
    {
      name: "Azize Diskotekte",
      artist: "Osman İşmen",
      art_cover: "osman_ismen_orkestrasi_azize_diskotekte.jpeg",
      thumbnail: "osman_ismen_orkestrasi_azize_diskotekte-thumbnail.jpeg",
      file: "osman_ismen_orkestrasi_azize_diskotekte.mp3",
    },
  ],
};

export { data };
