const template = document.createElement("template");
template.innerHTML = `
  <style>
    :host{}

    .container{
      display: flex;
      flex-direction: column;
      height: 100%;
      align-items: center;
      margin: 0 0.25rem;
    }


    .container2{
        margin: auto;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding-top: 2rem;
        padding-bottom: 2rem;
        // gap: 1rem;
    }

    img{
        max-width: 100%;
        height: auto;
        width: auto;
        flex: 1;
        border-radius: 1rem;
        // margin-top: 2rem;
        // margin-bottom: 2rem;
        
        
    }


    #artist_name:empty, #track_name:empty{
      display:none;
  
    }

    #artist_name, #track_name{
      font-weight: bold;
      font-size: 2rem;
    
    }

    #artist_name{
      align-self: flex-end;
      font-size: var(--preview-artist-size);
      margin-top: 0.25rem;
      color:var(--preview-artist-color)

    }

    #track_name{
      align-self: flex-start;
      font-size: var(--preview-track-size);
      margin-top: 1rem;
      margin-bottom: 0.25rem;
      color:var(--preview-track-color)

    }

      /* ----------------------------------------------
      * Generated by Animista on 2023-1-22 23:32:44
      * Licensed under FreeBSD License.
      * See http://animista.net/license for more info. 
      * w: http://animista.net, t: @cssanimista
      * ---------------------------------------------- */
      .swirl-in-fwd {
        -webkit-animation: swirl-in-fwd 0.8s ease-out both;
                animation: swirl-in-fwd 0.8s ease-out both;
         
      }

      /**
       * ----------------------------------------
       * animation swirl-in-fwd
       * ----------------------------------------
       */
      @-webkit-keyframes swirl-in-fwd {
        0% {
          -webkit-transform: rotate(-270deg) scale(0);
                  transform: rotate(-270deg) scale(0);
          opacity: 0;
        }
        100% {
          -webkit-transform: rotate(0) scale(1);
                  transform: rotate(0) scale(1);
          opacity: 1;
        }
      }
      @keyframes swirl-in-fwd {
        0% {
          -webkit-transform: rotate(-270deg) scale(0);
                  transform: rotate(-270deg) scale(0);
          opacity: 0;
        }
        100% {
          -webkit-transform: rotate(0) scale(1);
                  transform: rotate(0) scale(1);
          opacity: 1;
        }
      }

      .bounce-top {
        -webkit-animation: bounce-top 0.9s both;
        animation: bounce-top 0.9s both;
      }
      
      /* ----------------------------------------------
       * Generated by Animista on 2023-1-23 0:48:16
       * Licensed under FreeBSD License.
       * See http://animista.net/license for more info. 
       * w: http://animista.net, t: @cssanimista
       * ---------------------------------------------- */
      
      /**
       * ----------------------------------------
       * animation bounce-top
       * ----------------------------------------
       */
      @-webkit-keyframes bounce-top {
        0% {
          -webkit-transform: translateY(-45px);
          transform: translateY(-45px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
          opacity: 1;
        }
        24% {
          opacity: 1;
        }
        40% {
          -webkit-transform: translateY(-24px);
          transform: translateY(-24px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        65% {
          -webkit-transform: translateY(-12px);
          transform: translateY(-12px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        82% {
          -webkit-transform: translateY(-6px);
          transform: translateY(-6px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        93% {
          -webkit-transform: translateY(-4px);
          transform: translateY(-4px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        25%,
        55%,
        75%,
        87% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
        }
        100% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
          opacity: 1;
        }
      }
      @keyframes bounce-top {
        0% {
          -webkit-transform: translateY(-45px);
          transform: translateY(-45px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
          opacity: 1;
        }
        24% {
          opacity: 1;
        }
        40% {
          -webkit-transform: translateY(-24px);
          transform: translateY(-24px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        65% {
          -webkit-transform: translateY(-12px);
          transform: translateY(-12px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        82% {
          -webkit-transform: translateY(-6px);
          transform: translateY(-6px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        93% {
          -webkit-transform: translateY(-4px);
          transform: translateY(-4px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        25%,
        55%,
        75%,
        87% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
        }
        100% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
          opacity: 1;
        }
      }
      
      .bounce-bottom {
        -webkit-animation: bounce-bottom 0.9s both;
        animation: bounce-bottom 0.9s both;
      }
      
      /* ----------------------------------------------
       * Generated by Animista on 2023-1-23 0:48:26
       * Licensed under FreeBSD License.
       * See http://animista.net/license for more info. 
       * w: http://animista.net, t: @cssanimista
       * ---------------------------------------------- */
      
      /**
       * ----------------------------------------
       * animation bounce-bottom
       * ----------------------------------------
       */
      @-webkit-keyframes bounce-bottom {
        0% {
          -webkit-transform: translateY(45px);
          transform: translateY(45px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
          opacity: 1;
        }
        24% {
          opacity: 1;
        }
        40% {
          -webkit-transform: translateY(24px);
          transform: translateY(24px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        65% {
          -webkit-transform: translateY(12px);
          transform: translateY(12px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        82% {
          -webkit-transform: translateY(6px);
          transform: translateY(6px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        93% {
          -webkit-transform: translateY(4px);
          transform: translateY(4px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        25%,
        55%,
        75%,
        87% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
        }
        100% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
          opacity: 1;
        }
      }
      @keyframes bounce-bottom {
        0% {
          -webkit-transform: translateY(45px);
          transform: translateY(45px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
          opacity: 1;
        }
        24% {
          opacity: 1;
        }
        40% {
          -webkit-transform: translateY(24px);
          transform: translateY(24px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        65% {
          -webkit-transform: translateY(12px);
          transform: translateY(12px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        82% {
          -webkit-transform: translateY(6px);
          transform: translateY(6px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        93% {
          -webkit-transform: translateY(4px);
          transform: translateY(4px);
          -webkit-animation-timing-function: ease-in;
          animation-timing-function: ease-in;
        }
        25%,
        55%,
        75%,
        87% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
        }
        100% {
          -webkit-transform: translateY(0px);
          transform: translateY(0px);
          -webkit-animation-timing-function: ease-out;
          animation-timing-function: ease-out;
          opacity: 1;
        }
      }
      

  </style>
  
  <div id="container" class="container">
    <div class="container2">
    <div id="track_name" class="bounce-top">
    </div>
        <slot name="image">

          
          <img class="swirl-in-fwd artwork" id="artwork" src="./img/preview-placeholder.png" alt="A music record without a label">
        </slot>
        <div id="artist_name" class="bounce-bottom"></div>

    </div>
  </div>

`;

class Preview extends HTMLElement {
  #data = {
    player_key: null,
  };

  #image = null;
  #artistNameDiv = null;
  #trackNameDiv = null;

  constructor() {
    super();

    this.root = this.attachShadow({ mode: "closed" });
    const clone = template.content.cloneNode(true);
    this.root.append(clone);

    let link = document.createElement("link");
    link.rel = "stylesheet";
    // link.href = "./player.css";
    link.href = "../style/player.css";

    this.root.appendChild(link);

    link = document.createElement("link");
    link.rel = "stylesheet";
    link.href =
      "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0";
    this.root.appendChild(link);
    this.#image = this.root.getElementById("artwork");
    this.#artistNameDiv = this.root.getElementById("artist_name");
    this.#trackNameDiv = this.root.getElementById("track_name");
  }

  static get observedAttributes() {
    return ["player_key"];
  }

  set player_key(value) {
    this.#data.player_key = value;
    this.setAttribute("player_key", value);
  }
  get player_key() {
    return this.getAttribute("player_key");
  }

  attributeChangedCallback(attrName, oldVal, newVal) {
    if (oldVal != newVal) {
      attrName = attrName.toLowerCase().trim();

      switch (attrName) {
        case "player_key":
          this.#data.player_key = newVal;
          break;
      }
    }
  }

  replaceImage(ev) {
    console.log("now move: ", ev);

    this.#artistNameDiv.innerHTML = "";
    this.#trackNameDiv.innerHTML = "";

    this.#image.classList.remove("swirl-in-fwd");

    this.#trackNameDiv.classList.remove("bounce-top");
    this.#artistNameDiv.classList.remove("bounce-bottom");

    setTimeout(() => {
      this.#image.classList.add("swirl-in-fwd");
      this.#image.src = ev.image;
      if (ev.artist) {
        this.#artistNameDiv.innerHTML = `by ${ev.artist}`;
      }
      if (ev.name) {
        this.#trackNameDiv.innerHTML = ev.name;
      }

      this.#trackNameDiv.classList.add("bounce-top");
      this.#artistNameDiv.classList.add("bounce-bottom");
    }, 200);

    this.#image.animationPlayState = "running";
  }

  connectedCallback() {
    // console.log("inside connected call back", this.#data.player_key);
    document.addEventListener(`play-track-${this.#data.player_key}`, (ev) => {
      this.replaceImage.call(this, ev.detail);
    });
  }
}

customElements.define("ulut0002-preview", Preview);
export default Preview;
