import Controls from "./controls.js";

const template = document.createElement("template");
template.innerHTML = `
  <style>

        :host{
          display: block;
          height: 100%;
        }

        .container{
          display: flex;
          flex-direction: column !important;
          justify-content: center !important;
          align-items: center !important;
          height: 100% !important;
          background: inherit;
          background-image: inherit;
        }

        #artist_name:empty, #track_name:empty{
          display:none;  
        }

        .img{
          border-radius: var( --preview-image-border-radius);
          max-width: 100%;
          height: auto;
          width: auto;
        }

        .artwork_container{
          margin: auto 5vw; 
          align-self: center;
          display: flex;
          flex-direction: column;
          padding-top: 4rem;
          padding-bottom: 4rem;
        }

        #artist_name{
          font-size: var(--preview-artist-size);
          margin-top: 0.25rem;
          color:var(--preview-artist-color);
          margin-right: 0.75rem;
          align-self: flex-end;
          font-weight: bold;
        }

        #track_name{
          font-size: var(--preview-track-size);
          margin-left: 0.50rem;
          color:var(--preview-track-color);
          align-self: flex-start;
          font-weight: bold;
        }

        .controls{
          max-width: 100%;
          width: 100%;
        }

        @media only screen and (min-width: 45rem) {
          .artwork_container{
            padding-top: 2rem;
            padding-bottom: 2rem;
          }
        }



          /* ----------------------------------------------
          * Generated by Animista on 2023-1-22 23:32:44
          * Licensed under FreeBSD License.
          * See http://animista.net/license for more info. 
          * w: http://animista.net, t: @cssanimista
          * ---------------------------------------------- */
          .swirl-in-fwd {
            -webkit-animation: swirl-in-fwd 0.8s ease-out both;
                    animation: swirl-in-fwd 0.8s ease-out both;
            
          }

          /**
           * ----------------------------------------
           * animation swirl-in-fwd
           * ----------------------------------------
           */
          @-webkit-keyframes swirl-in-fwd {
            0% {
              -webkit-transform: rotate(-270deg) scale(0);
                      transform: rotate(-270deg) scale(0);
              opacity: 0;
            }
            100% {
              -webkit-transform: rotate(0) scale(1);
                      transform: rotate(0) scale(1);
              opacity: 1;
            }
          }
          @keyframes swirl-in-fwd {
            0% {
              -webkit-transform: rotate(-270deg) scale(0);
                      transform: rotate(-270deg) scale(0);
              opacity: 0;
            }
            100% {
              -webkit-transform: rotate(0) scale(1);
                      transform: rotate(0) scale(1);
              opacity: 1;
            }
          }

          .bounce-top {
            -webkit-animation: bounce-top 0.9s both;
            animation: bounce-top 0.9s both;
          }
          
          /* ----------------------------------------------
          * Generated by Animista on 2023-1-23 0:48:16
          * Licensed under FreeBSD License.
          * See http://animista.net/license for more info. 
          * w: http://animista.net, t: @cssanimista
          * ---------------------------------------------- */
          
          /**
           * ----------------------------------------
           * animation bounce-top
           * ----------------------------------------
           */
          @-webkit-keyframes bounce-top {
            0% {
              -webkit-transform: translateY(-45px);
              transform: translateY(-45px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
              opacity: 1;
            }
            24% {
              opacity: 1;
            }
            40% {
              -webkit-transform: translateY(-24px);
              transform: translateY(-24px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            65% {
              -webkit-transform: translateY(-12px);
              transform: translateY(-12px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            82% {
              -webkit-transform: translateY(-6px);
              transform: translateY(-6px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            93% {
              -webkit-transform: translateY(-4px);
              transform: translateY(-4px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            25%,
            55%,
            75%,
            87% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
            }
            100% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
              opacity: 1;
            }
          }
          @keyframes bounce-top {
            0% {
              -webkit-transform: translateY(-45px);
              transform: translateY(-45px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
              opacity: 1;
            }
            24% {
              opacity: 1;
            }
            40% {
              -webkit-transform: translateY(-24px);
              transform: translateY(-24px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            65% {
              -webkit-transform: translateY(-12px);
              transform: translateY(-12px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            82% {
              -webkit-transform: translateY(-6px);
              transform: translateY(-6px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            93% {
              -webkit-transform: translateY(-4px);
              transform: translateY(-4px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            25%,
            55%,
            75%,
            87% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
            }
            100% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
              opacity: 1;
            }
          }
          
          .bounce-bottom {
            -webkit-animation: bounce-bottom 0.9s both;
            animation: bounce-bottom 0.9s both;
          }
          
          /* ----------------------------------------------
          * Generated by Animista on 2023-1-23 0:48:26
          * Licensed under FreeBSD License.
          * See http://animista.net/license for more info. 
          * w: http://animista.net, t: @cssanimista
          * ---------------------------------------------- */
          
          /**
           * ----------------------------------------
           * animation bounce-bottom
           * ----------------------------------------
           */
          @-webkit-keyframes bounce-bottom {
            0% {
              -webkit-transform: translateY(45px);
              transform: translateY(45px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
              opacity: 1;
            }
            24% {
              opacity: 1;
            }
            40% {
              -webkit-transform: translateY(24px);
              transform: translateY(24px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            65% {
              -webkit-transform: translateY(12px);
              transform: translateY(12px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            82% {
              -webkit-transform: translateY(6px);
              transform: translateY(6px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            93% {
              -webkit-transform: translateY(4px);
              transform: translateY(4px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            25%,
            55%,
            75%,
            87% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
            }
            100% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
              opacity: 1;
            }
          }
          @keyframes bounce-bottom {
            0% {
              -webkit-transform: translateY(45px);
              transform: translateY(45px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
              opacity: 1;
            }
            24% {
              opacity: 1;
            }
            40% {
              -webkit-transform: translateY(24px);
              transform: translateY(24px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            65% {
              -webkit-transform: translateY(12px);
              transform: translateY(12px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            82% {
              -webkit-transform: translateY(6px);
              transform: translateY(6px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            93% {
              -webkit-transform: translateY(4px);
              transform: translateY(4px);
              -webkit-animation-timing-function: ease-in;
              animation-timing-function: ease-in;
            }
            25%,
            55%,
            75%,
            87% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
            }
            100% {
              -webkit-transform: translateY(0px);
              transform: translateY(0px);
              -webkit-animation-timing-function: ease-out;
              animation-timing-function: ease-out;
              opacity: 1;
            }
          }
  </style>
  
  <div id="container" class="container">
    <div class="artwork_container">
      <div id="track_name" class="bounce-top"></div>
      <slot name="image" class="artwork">
        <img
          class="swirl-in-fwd img"
          id="artwork"
          src="./img/preview-placeholder.png"
          alt="A music record without a label"
        />
      </slot>
      <div id="artist_name" class="bounce-bottom"></div>
    </div>
    <ulut0002-controls id="controls" class="controls"></ulut0002-controls>
  </div>


`;

class Preview extends HTMLElement {
  #data = {
    player_key: null,
  };

  #image = null;
  #artistNameDiv = null;
  #trackNameDiv = null;
  #controlDiv = null;

  constructor() {
    super();

    this.root = this.attachShadow({ mode: "closed" });
    const clone = template.content.cloneNode(true);
    this.root.append(clone);

    let link = document.createElement("link");
    link.rel = "stylesheet";
    // link.href = "./player.css";
    link.href = "../style/player.css";

    this.root.appendChild(link);

    link = document.createElement("link");
    link.rel = "stylesheet";
    link.href =
      "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0";
    this.root.appendChild(link);
    this.#image = this.root.getElementById("artwork");
    this.#artistNameDiv = this.root.getElementById("artist_name");
    this.#trackNameDiv = this.root.getElementById("track_name");
    this.#controlDiv = this.root.getElementById("controls");
  }

  static get observedAttributes() {
    return ["player_key"];
  }

  set player_key(value) {
    this.#data.player_key = value;
    this.setAttribute("player_key", value);
  }
  get player_key() {
    return this.getAttribute("player_key");
  }

  attributeChangedCallback(attrName, oldVal, newVal) {
    if (oldVal != newVal) {
      attrName = attrName.toLowerCase().trim();

      switch (attrName) {
        case "player_key":
          this.#data.player_key = newVal;
          this.#controlDiv.setAttribute("player_key", this.player_key);
          break;
      }
    }
  }

  replaceImage(ev) {
    console.log("values: ", "1: ", ev.image, "2: ", this.#image.src);

    /*
    TODO: 

      val 1:  ./img/paul_mccartney_michael_jackson_say_say_say.jpeg 
      val 2:  http://127.0.0.1:5501/img/paul_mccartney_michael_jackson_say_say_say.jpeg

     must find a way to match them
    */
    if (ev.image.toLowerCase() == this.#image.src.toLowerCase()) {
      console.log("caught");
      return;
    }
    // return;
    this.#artistNameDiv.innerHTML = "";
    this.#trackNameDiv.innerHTML = "";

    this.#image.classList.remove("swirl-in-fwd");

    this.#trackNameDiv.classList.remove("bounce-top");
    this.#artistNameDiv.classList.remove("bounce-bottom");

    setTimeout(() => {
      this.#image.src = ev.image;
      if (ev.artist) this.#artistNameDiv.innerHTML = `by ${ev.artist}`;
      if (ev.name) this.#trackNameDiv.innerHTML = ev.name;

      this.#trackNameDiv.classList.add("bounce-top");
      this.#artistNameDiv.classList.add("bounce-bottom");
      this.#image.classList.add("swirl-in-fwd");
    }, 200);

    this.#image.animationPlayState = "running";
  }

  connectedCallback() {
    // console.log("inside connected call back", this.#data.player_key);
    document.addEventListener(`play-track-${this.#data.player_key}`, (ev) => {
      this.replaceImage.call(this, ev.detail);
    });
    this.#controlDiv.setAttribute("player_key", this.player_key);
  }
}

customElements.define("ulut0002-preview", Preview);
export default Preview;
